### ISSUE TITLE
tinydng #including headers within custom namespace causes ambiguous declaration

### ISSUE THREAD

**Issue by wkjarosz** [syoyo/tinydngloader#6]
#including other headers within your own tinydng namespace causes issues in the parent code. This declares functions outside of their expected scope, and causes ambiguous declaration issues. See for instance this appveyor build log: 

https://ci.appveyor.com/project/wkjarosz/hdrview/build/1.0.152/job/f1bi9puchcrv9i4v

(search for "error" on the page)

Here #including some standard headers within the tinydng namespace means that on Windows, _wassert is now defined both within the global namespace and as tinydng::_wassert, and the compiler doesn't know which one to use.

All #includes should be moved to the global scope to avoid introducing functions into unexpected scope.

**Comment by syoyo** [comment]
`stb_image.h` was included inside tinydng namespace. I have moved to global namespace in this commit

**Comment by wkjarosz** [comment]
Seems to work now. Thanks!

**Comment by syoyo** [comment]
Thanks for reporting!
